name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  php_cs_fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Run Script
      run: testing/run_cs_check.sh

  php_code_sniffer:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: composer global require squizlabs/php_codesniffer
    - name: Run PHPCS Code Style Checker
      run: ~/.composer/vendor/bin/phpcs --standard=phpcs-ruleset.xml -p -s

  phpstan_static_analysis:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Run Script
      run: |
        composer global require phpstan/phpstan
        for dir in $(find * -type d -name src -not -path 'appengine/*' -not -path '*/vendor/*' -exec dirname {} \;);
        do
          composer install --working-dir=$dir --ignore-platform-reqs
          echo "<?php require_once 'testing/sample_helpers.php';require_once '$dir/vendor/autoload.php';" > autoload.php
          ~/.composer/vendor/bin/phpstan analyse $dir/src --autoload-file=autoload.php
        done
